@startuml JCalculator
left to right direction
class JCalculator {
  - empty : String[]

  - jNumber : JTextField
  - jStack : JList
  - constraints : GridBagConstraints

  + JCalculator()
  + update()
  + addOperatorButton(String name, int x, int y, Color color, Operator operator)
}


JCalculator ..> State : uses
JCalculator ..> JButton : has
JCalculator ..> JTextField : creates
JCalculator ..> JList : creates
JCalculator ..> GridBagConstraints : uses
JButton ..> Operator : uses

class JTextField {
  + setText(String text)
  + setEditable(boolean editable)
  + setBackground(Color color)
  + setHorizontalAlignment(int alignment)
}

class JList {
  + setListData(Object[] data)
  + setFont(Font font)
  + setVisibleRowCount(int count)
}

class GridBagConstraints {
  + int fill
  + int gridx
  + int gridy
  + int gridwidth
  + int gridheight
  + Insets insets
}

abstract class Operator {
  + execute()
}

JCalculator --|> JFrame : extends

@enduml
