@startuml
skinparam linetype polyline
skinparam groupInheritance 2
left to right direction
package "Operators" {
  abstract class Operator {
    {abstract} execute()
    + executeBinaryOperation(double operand1, double operand2, State state, BinaryOperation operation)
    + compute(double operand1, double operand2)
  }

  class BackSpace extends Operator {
    + execute()
  }

  class ClearError extends Operator {
    + execute()
  }

  class Clear extends Operator {
    + execute()
  }

  class MemoryRecall extends Operator {
    + execute()
  }

  class MemoryStore extends Operator {
    + execute()
  }

  class Digit extends Operator {
    - int digit
    + Digit(int digit)
    + execute()
  }

  abstract class UnaryOperation extends Operator {
    + UnaryOperation(UnaryFunction operation)
    + execute()
  }

  class ChangeSign extends Operator {
    + execute()
  }

  class AppendDot extends Operator {
    + execute() 
  }

  class Reciprocal extends UnaryOperation {
    + Reciprocal()
  }

  class Square extends UnaryOperation {
    + Square()
  }

  class SquareRoot extends UnaryOperation {
    + SquareRoot()
  }

  abstract class BinaryOperation extends Operator {
    + execute()
    {abstract} compute(double operand1, double operand2)
  }

  class Addition extends BinaryOperation {
    + compute(double operand1, double operand2)
  }

  class Subtraction extends BinaryOperation {
    + compute(double operand1, double operand2)
  }

  class Multiplication extends BinaryOperation {
    + compute(double operand1, double operand2)
  }

  class Division extends BinaryOperation {
    + compute(double operand1, double operand2)
  }

  class Enter extends Operator {
    + execute()
  }

}
@enduml
