@startuml
skinparam linetype polyline
skinparam groupInheritance 2
left to right direction
package "Operators" {
  abstract class Operator {
    {abstract} void execute()
    {abstract} double compute(double operand1, double operand2)
  }

  class BackSpace extends Operator {
    + void execute()
  }

  class ClearError extends Operator {
    + void execute()
  }

  class Clear extends Operator {
    + void execute()
  }

  class MemoryRecall extends Operator {
    + void execute()
  }

  class MemoryStore extends Operator {
    + void execute()
  }

  class Digit extends Operator {
    - int digit
    + Digit(int digit)
    + void execute()
  }

  abstract class BinaryOperation extends Operator {
    + void execute()
    {abstract} double compute(double operand1, double operand2)
  }

  class ChangeSign extends Operator {
    + void execute()
  }

  class AppendDot extends Operator {
    + void execute()
  }

  class Reciprocal extends Operator {
    + void execute()
  }

  class Square extends Operator {
    + void execute()
  }

  class SquareRoot extends Operator {
    + void execute()
  }

  class Addition extends BinaryOperation {
    + double compute(double operand1, double operand2)
  }

  class Subtraction extends BinaryOperation {
    + double compute(double operand1, double operand2)
  }

  class Multiplication extends BinaryOperation {
    + double compute(double operand1, double operand2)
  }

  class Division extends BinaryOperation {
    + double compute(double operand1, double operand2)
  }

  class Enter extends Operator {
    + void execute()
  }

}
@enduml
