@startuml Stack

class Stack<T> {
  - elements: T[]
  - size: int
  - static INITIAL_CAPACITY: int = 10
  + Stack()
  + push(item: T): void
  + pop(): T
  + toString(): String
  + toArray(): T[]
  + iterator(): Iterator<T>
  - resize(newCapacity: int): void
}

class StackIterator {
  - current: int
  + hasNext(): boolean
  + next(): T
}

Stack "1" *-- "1" StackIterator : uses
Stack ..> Iterator : implements

@enduml
