@startuml Stack

class Stack<T> {
  - T[] elements
  - int size = 0
  - static final int INITIAL_CAPACITY = 10
- void resize(int newCapacity)

  + Stack()
  + void push(T item)
  + T pop()
  + String toString()
  + T[] toArray()
  + Iterator<T> iterator()
  + boolean isEmpty() : boolean
  + int size() : int
}

class StackIterator {
  - int current
  + boolean hasNext() : boolean
  + T next() : T
}

Stack "1" *-- "1" StackIterator : uses
Stack ..> Iterator : implements

@enduml
