@startuml
class State {
    - String value = ""
    - String memory = "0"
    - String error = ""
    - boolean hasError = false
    - boolean isMutable = true
    - double operand1 = 0
    - Operator currentOperator = null
    - boolean waitingForNextOperand = false
    - boolean clearedOnNextInput = false
    + State()
    + static State getState() : State
    + void clearError()
    + void appendValue(int x)
    + void appendDot()
    + void prepareForNextOperand()
    + void changeSign()
    + void reciprocal()
    + void square()
    + void squareRoot()
    + void delLastValue()
    + void storeValue()
    + void recallValue()
    + String getValueString() : String
    + String getMemory() : String
    + double value() : double
    + void setValue(double x)
    - String formatValue(double x) : String
    + void setError(String errorMessage)
    + void setOperand1(double operand1)
    + double getOperand1() : double
    + void setCurrentOperator(Operator operator)
    + Operator getCurrentOperator() : Operator
    + boolean isWaitingForNextOperand() : boolean
    + void setWaitingForNextOperand(boolean waiting)
    + void setClearedOnNextInput(boolean clearedOnNextInput)
}

Operators --> State : "manipule"
@enduml
