@startuml
class State {
    - instance : State
    - value : String
    - memory : String
    - error : String
    - hasError : boolean
    - isMutable : boolean
    - currentOperator : Operator
    - waitingForNextOperand : boolean
    - clearedOnNextInput : boolean
    - stack : Stack<Double>
    - formatValue(double x)
    - clearStack()

    + State()
    + getState()
    + clearError()
    + appendValue(int x)
    + appendDot()
    + prepareForNextOperand()
    + changeSign()
    + delLastValue()
    + storeValue()
    + recallValue()
    + getValueString()
    + double value()
    + setValue(double x)
    + setError(String errorMessage)
    + setCurrentOperator(Operator operator)
    + getCurrentOperator()
    + boolean isWaitingForNextOperand()
    + setWaitingForNextOperand(boolean waiting)
    + isStackEmpty()
    + pushToStack(double value)
    + popFromStack()
    + String stackToString()
    + stackToArray()
    + clear()
    + stackSize()
}
@enduml
